# Generated by Django 4.0.2 on 2022-02-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=200)),
                ('facebook', models.URLField(blank=True, help_text='Dirección de facebook de la empresa', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Dirección de instrgram de la empresa', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Dirección de twitter de la empresa', null=True)),
            ],
            options={
                'verbose_name': 'contactos',
                'verbose_name_plural': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(help_text='Escoja una imagen referencial a la historia', upload_to='static/admin/images/empresa')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'MISION'), ('2', 'VISION'), ('3', 'VALORES')], default='1', max_length=50)),
                ('imagen', models.ImageField(help_text='Escoja una imagen referencial al tipo de plan estratégico', upload_to='static/admin/images/empresa')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
                ('respuesta', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'PreguntaFrecuente',
                'verbose_name_plural': 'PreguntasFrecuentes',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo_ocupado', models.CharField(max_length=100)),
                ('imagen', models.ImageField(help_text='Escoja una imagen referencial a al personaje del equipo', upload_to='static/admin/images/empresa')),
                ('descripción', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
